// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MolServiceDatabaseImplement;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MolServiceDatabaseImplement.Migrations
{
    [DbContext(typeof(MOLServiceDatabase))]
    partial class MOLServiceDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("CoreSystemId")
                        .HasColumnType("integer");

                    b.Property<bool>("NotUseInSchedule")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoreSystemId")
                        .IsUnique();

                    b.HasIndex("Number");

                    b.ToTable("classrooms", (string)null);
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.EquipmentMovementHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialTechnicalValueId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaterialTechnicalValueId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MoveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialTechnicalValueId");

                    b.HasIndex("MaterialTechnicalValueId1");

                    b.ToTable("equipment_movement_histories", (string)null);
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.MaterialResponsiblePerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("material_responsible_persons", (string)null);
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.MaterialTechnicalValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassroomId1")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MaterialResponsiblePersonId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaterialResponsiblePersonId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("ClassroomId1");

                    b.HasIndex("MaterialResponsiblePersonId");

                    b.HasIndex("MaterialResponsiblePersonId1");

                    b.ToTable("material_technical_values", (string)null);
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.MaterialTechnicalValueGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("material_technical_value_groups", (string)null);
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.MaterialTechnicalValueRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("MaterialTechnicalValueGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaterialTechnicalValueGroupId1")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialTechnicalValueId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaterialTechnicalValueId1")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialTechnicalValueGroupId");

                    b.HasIndex("MaterialTechnicalValueGroupId1")
                        .HasDatabaseName("IX_material_technical_value_records_MaterialTechnicalValueGro~1");

                    b.HasIndex("MaterialTechnicalValueId");

                    b.HasIndex("MaterialTechnicalValueId1");

                    b.ToTable("material_technical_value_records", (string)null);
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SoftwareDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SoftwareK")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SoftwareKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("softwares", (string)null);
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.SoftwareRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MaterialTechnicalValueId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaterialTechnicalValueId1")
                        .HasColumnType("integer");

                    b.Property<string>("SetupDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("integer");

                    b.Property<int?>("SoftwareId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialTechnicalValueId");

                    b.HasIndex("MaterialTechnicalValueId1");

                    b.HasIndex("SoftwareId");

                    b.HasIndex("SoftwareId1");

                    b.ToTable("software_records", (string)null);
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.EquipmentMovementHistory", b =>
                {
                    b.HasOne("MolServiceDatabaseImplement.Models.MaterialTechnicalValue", "MaterialTechnicalValue")
                        .WithMany()
                        .HasForeignKey("MaterialTechnicalValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MolServiceDatabaseImplement.Models.MaterialTechnicalValue", null)
                        .WithMany("EquipmentMovementHistories")
                        .HasForeignKey("MaterialTechnicalValueId1")
                        .HasConstraintName("FK_equipment_movement_histories_material_technical_values_Mat~1");

                    b.Navigation("MaterialTechnicalValue");
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.MaterialTechnicalValue", b =>
                {
                    b.HasOne("MolServiceDatabaseImplement.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MolServiceDatabaseImplement.Models.Classroom", null)
                        .WithMany("MaterialTechnicalValues")
                        .HasForeignKey("ClassroomId1");

                    b.HasOne("MolServiceDatabaseImplement.Models.MaterialResponsiblePerson", "MaterialResponsiblePerson")
                        .WithMany()
                        .HasForeignKey("MaterialResponsiblePersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MolServiceDatabaseImplement.Models.MaterialResponsiblePerson", null)
                        .WithMany("MaterialTechnicalValues")
                        .HasForeignKey("MaterialResponsiblePersonId1")
                        .HasConstraintName("FK_material_technical_values_material_responsible_persons_Mat~1");

                    b.Navigation("Classroom");

                    b.Navigation("MaterialResponsiblePerson");
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.MaterialTechnicalValueRecord", b =>
                {
                    b.HasOne("MolServiceDatabaseImplement.Models.MaterialTechnicalValueGroup", "MaterialTechnicalValueGroup")
                        .WithMany()
                        .HasForeignKey("MaterialTechnicalValueGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MolServiceDatabaseImplement.Models.MaterialTechnicalValueGroup", null)
                        .WithMany("MaterialTechnicalValueRecords")
                        .HasForeignKey("MaterialTechnicalValueGroupId1")
                        .HasConstraintName("FK_material_technical_value_records_material_technical_value_~1");

                    b.HasOne("MolServiceDatabaseImplement.Models.MaterialTechnicalValue", "MaterialTechnicalValue")
                        .WithMany()
                        .HasForeignKey("MaterialTechnicalValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MolServiceDatabaseImplement.Models.MaterialTechnicalValue", null)
                        .WithMany("MaterialTechnicalValueRecords")
                        .HasForeignKey("MaterialTechnicalValueId1")
                        .HasConstraintName("FK_material_technical_value_records_material_technical_values~1");

                    b.Navigation("MaterialTechnicalValue");

                    b.Navigation("MaterialTechnicalValueGroup");
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.SoftwareRecord", b =>
                {
                    b.HasOne("MolServiceDatabaseImplement.Models.MaterialTechnicalValue", "MaterialTechnicalValue")
                        .WithMany()
                        .HasForeignKey("MaterialTechnicalValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MolServiceDatabaseImplement.Models.MaterialTechnicalValue", null)
                        .WithMany("SoftwareRecords")
                        .HasForeignKey("MaterialTechnicalValueId1")
                        .HasConstraintName("FK_software_records_material_technical_values_MaterialTechnic~1");

                    b.HasOne("MolServiceDatabaseImplement.Models.Software", "Software")
                        .WithMany()
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MolServiceDatabaseImplement.Models.Software", null)
                        .WithMany("SoftwareRecords")
                        .HasForeignKey("SoftwareId1");

                    b.Navigation("MaterialTechnicalValue");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.Classroom", b =>
                {
                    b.Navigation("MaterialTechnicalValues");
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.MaterialResponsiblePerson", b =>
                {
                    b.Navigation("MaterialTechnicalValues");
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.MaterialTechnicalValue", b =>
                {
                    b.Navigation("EquipmentMovementHistories");

                    b.Navigation("MaterialTechnicalValueRecords");

                    b.Navigation("SoftwareRecords");
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.MaterialTechnicalValueGroup", b =>
                {
                    b.Navigation("MaterialTechnicalValueRecords");
                });

            modelBuilder.Entity("MolServiceDatabaseImplement.Models.Software", b =>
                {
                    b.Navigation("SoftwareRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
